### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-DuilioAquino10#2]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-DuilioAquino10/files/9419166/Infografia.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 19/20


Faltaron referencias.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
